# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Keke Arif"



author:
  name:             Keke Arif
  #facebook:         your-id
  twitter:          keke_arif
  github:           kekearif
  #linkedin:         your-id
  #medium:           your-id
  #tumblr:           your-id
  email:            kekearif@googlemail.com
  rss:              feed

# Google-analytics
google-analytics:
  id:               "UA-89675183-1" # Can't anyone just copy this?

# Disqus
disqus:
  id:               "kekearif"

#URL
#url:               "http://www.kekearif.com"
#url:               "localhost:4000"
baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Taipei
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM
highlighter: rouge

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  #- name:           "TIL"
    #url:            "https://github.com/kekearif/TIL"
  #- name:           "Github"
    #url:            "https://github.com/kekearif"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji

exclude:            [vendor]
